### ISSUE TITLE
Search button as it is read by NVDA?

### ISSUE THREAD

**Issue by austin-2015** [WordPress/twentysixteen#223] opened 2015-09-19 20:30 UTC
First of all, thank you for the AMAZING, awesome accessibility for WordPress themes -- it is so greatly appreciated. 

As a NON-EXPERT user of assistive technology, I found myself a little confused over "how" the search function was handled by NVDA 2015.2 on the Twenty Sixteen theme.  Search was (I believe) correctly read out during the first pass, but there was a follow-on announcement as a "complementary"  search button (brief video to illustrate at https://youtu.be/RkjAnvgI4mw see time frame 0:48).   Because of this, visually, I started looking for a button, and cognitively, I wondered if there wasn't two components to the landmark search feature. 

I consulted "Using ARIA landmarks to identify regions of a page" for further guidance, but was unclear how to handle a search role within a component that was given a role of complementary. http://www.w3.org/TR/wai-aria/roles#search

The code that generates this seems to be the complementary role of the widget area (div id="secondary")

Would it be possible for those with more expertise than me to look at this a little more closely? 

Again, thank you so much for everything you do here.

**Comment by karmatosed** [comment] 2015-09-20 09:01
Sure, lets get @davidakennedy to give an opinion on this? Hope that's ok DK :)

**Comment by davidakennedy** [comment] 2015-09-21 15:15
Hi there! Thanks for reporting this. :smile:.

As  far as I can tell, this is expected behavior. The extra bit of output you hear is the screen reader reading out the ARIA landmark roles. You're hearing extra because you're inside of a `search` role, nested inside of a `complementary` role. The search button is hidden off screen, so that's why you don't see it visually, but it's there for users who prefer to have a button to activate the search form, rather than just hitting enter.

 I will double check on this with someone who's more familiar with NVDA, just to make sure.

Thanks again!

**Comment by austin-2015** [comment] 2015-09-22 11:55
Thank you, David!  I appreciate the second look, for sure!

Full disclosure, I'm probably way too close to a personal "scenario" of expectations, due to one friend I'm working with.  He has multiple disabilities, including low vision and poor motor skills.  Though not blind, he's been looking for a text-to-speech capability, most of which cost a lot of money.   As NVDA is free, we were considering its use for his case.  I don't know how common this is to low-vision users, and I suspect we don't have a good way of knowing right now, as it is hard to capture these kinds of problems in surveys.

But it was the reason behind the question of the visibility of the button.  At the end of the day, it would be a bit of minor confusion for him to hear "button" but not see it on the screen.

The bigger issue is the "search" function.   From what I have seen, not only from him, but from others with certain disabilities, is that they use the search function for much more than just searching--they use it as a kind of navigational landmark, when the page becomes complicated for them.

To that end, of we could remove the "aural" association of the complementary role with the search role, I think it may help things--I'm talking an enhancement here, to make things more clear to those who rely on the search function for so much.

I understand that this is probably expected behavior, but would it be out of line to consider an enhancement to recommend that the search function be placed in a separate segment that does not fall under a section that is labeled complementary?  

If it is not out of line to recommend such enhancements, I do have a few ideas I could share.  But of course, I say this as an individual who has a "personal agenda" for a friend with disabilities, so I have a hard time knowing if such recommendations are reasonable in the bigger picture! :-)

Thank you for the consideration!  I really appreciate it!

**Comment by davidakennedy** [comment] 2015-09-24 17:45
Some of this is an issue with the search form, and its markup, provided by Core. A ticket has been created: https://core.trac.wordpress.org/ticket/33952

We can probably close this, and attack it Core.

**Closed as completed** 2015-09-24 19:17 UTC
Labels: second opinion
