### ISSUE TITLE
Reserved Toolbar space on wp-signup.php

### ISSUE THREAD

**Issue by DrewAPicture** [WordPress/twentysixteen#353] opened 2015-10-23 03:49 UTC
Looks like space is being reserved at the top of the window for the Toolbar when logged-in and viewing wp-signup.php. The Toolbar isn't displayed on wp-signup.php, so it looks a little wonky.

Seems like it's probably tied to the `.admin-bar` body class. Unchecking the "Show Toolbar when viewing site" option removes that class and therefore removes the reserved space.

![Twenty Sixteen Signup](http://cl.ly/image/1A1V1n2w353H/Screen%20Shot%202015-10-22%20at%209.33.06%20PM.png)

**Comment by iamtakashi** [comment] 2015-10-23 04:00
This probably better to be filed as a core issue because the body class shouldn't be there when there is no admin bar, should it?

**Comment by DrewAPicture** [comment] 2015-10-23 05:42
I brought it up here because this seems to be the only default that has this problem. I've always been under the impression that best practice was to mold around the Toolbar being injected by core (or not) rather than reserving the space with the expectation that it will always be there if the body class is present.

My hesitation In removing the class via core, is that I wonder if we'd introduce unexpected results for themes expecting it to be there – though I agree we shouldn't be outputting that class if we aren't going to show it.

**Comment by iamtakashi** [comment] 2015-10-23 06:01
I think it's reasonable for themes to use the body class to adjust the style. That's one of the purpose of the body class. I understand your concern and I can't see all the possibility of the outcome of removing the class from the page but, to me it's a legitimate bug in core and I'm glad you spotted it. But I still believe It'd be best to fix in core rather than making themes deal with it.

**Comment by iamtakashi** [comment] 2015-10-23 16:26
The consensus among the team is that this should be fixed in core as the body class should not be there when the admin bar isn't displayed.

@DrewAPicture, Could you move this to core trac? It will be beneficial to be fixed in core for a long term.

**Comment by DrewAPicture** [comment] 2015-10-23 21:03
After some digging, looks like a core bug introduced three years ago was preventing the Toolbar from being displayed on wp-signup.php. We'll handle that in https://core.trac.wordpress.org/ticket/34418.

On the reserved space issue, I respect the team's decision, but disagree. I think we're setting a poor example by doing it. It should just work like many many other themes have worked before it (including every previous default theme in my testing).

**Comment by iamtakashi** [comment] 2015-10-23 22:03
@DrewAPicture, I'm glad to see the issue is going to be handled in core. Thanks.

It's hard for me to understand why you think this is a poor example. Just to explain, in order to make the top part of the border stay in the appropriate position even you scroll the page, the position of the element has to be specified. And it depends on the existence of the admin bar and its height, the value of the position has to adjusted so that it stays at the top of page. In my opinion there is nothing wrong with this technique utilising the body class.

To me, it's irrelevant whether past default themes didn't have issue with the body class or not because each themes is different as they should be, and this fake border treatment is unique to Twenty Sixteen. I'm pretty sure themes that have sticky/fixed element at the top will share this issue caused by the body class.

Twenty Fourteen tried to avoid <a href="https://core.trac.wordpress.org/ticket/28573">the issue</a> by <a href="https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentyfourteen/functions.php#L411">disabling the sticky header on the page</a> but we shouldn't have had to, because this caused inconsistent behaviour of the header.

Not only that, when you have a header image in Twenty Fourteen, there is still a visual bug on the page because of the body class. So, regardless whether it's relevant or not, a past default theme does have an issue caused by the body class anyway.

![screen shot 2015-10-23 at 22 33 10](https://cloud.githubusercontent.com/assets/908665/10705769/4e7545d6-79d8-11e5-823d-5e15e9c93864.png)

Again, I'm glad to see this is handled by core and all of this will be fixed when the issue is fixed in core. I didn't want beat a dead horse but I just wanted to clarify why I think this needs to be handled by core.

**Closed as completed** 2015-10-24 12:45 UTC
