### ISSUE TITLE
Category/Tag spacing bug

### ISSUE THREAD

**Issue by maharzan** [WordPress/twentysixteen#59] opened 2015-08-31 13:20 UTC
At some point there is this little design issue. When there are two or more categories, it seems the padding between the categories list and tags list in entry footer become larger than when its only 1 category. Looks like this css is the issue

```
.entry-footer > span:not(:last-child):after {
  padding: 0 0.538461538em;
}
```

That padding appears on the next line which triggers that space.

Here is the screenshot that should be self explanatory.

![padding-issue](https://cloud.githubusercontent.com/assets/883993/9579545/2e5f3778-5013-11e5-8732-da7ddfd229c6.png)

**Comment by karpstrucking** [comment] 2015-08-31 13:28
This might be a duplicate of, or related to, #37

**Comment by karmatosed** [comment] 2015-08-31 15:24
I 'think' it's a duplicate. For now, I'm closing but we can review.

**Closed as completed by karmatosed** 2015-08-31 15:24 UTC
Labels: duplicate

**Comment by mor10** [comment] 2015-09-04 20:36
It's a duplicate. https://github.com/WordPress/twentysixteen/pull/38 fixes this issue.
