### ISSUE TITLE
Page border causes Read More link to miss first line of text

### ISSUE THREAD

**Issue by theukedge** [WordPress/twentysixteen#413] opened 2016-01-13 16:25 UTC
The large border around the page is applied in such a way that when jumping to an anchor or CSS ID class, as with the Read More link, the point in the page is hidden beneath the page border. As such, when you click on the Read More link:

![dave-clements---brit-in-the-states 2](https://cloud.githubusercontent.com/assets/3171242/12300066/d1ae3b20-b9e7-11e5-8165-b03276c6f49a.png)

you get taken to the right place in the text, except that the first line of text (give or take) is covered by that border. Is there any adjustment that we can make to move it to the right point in the text without the user having to search for where they should be reading from?

![the-liberation-project](https://cloud.githubusercontent.com/assets/3171242/12300160/3d0b5d26-b9e8-11e5-9704-71f6cec82a40.png)

**Comment by iamtakashi** [comment] 2016-02-04 14:10
It's not impossible to resolve this with JS but it's really minor and it hasn't been gathering interest from anybody so far. Does anybody interested?

**Comment by iamtakashi** [comment] 2016-03-09 21:43
Since the issue is really minor and it's not getting any interest from anybody, I'm closing this as wontfix. Thanks for the suggestion though.

**Closed as completed by iamtakashi** 2016-03-09 21:43 UTC
Labels: wontfix
