### ISSUE TITLE
Images distorted and rotated 90 degrees on mobile display

### ISSUE THREAD

**Issue by mjglsn** [WordPress/twentysixteen#396] opened 2015-12-16 17:04 UTC
I created a post with no text just images, inserted 10 or so images into the post using the Media tool, and published. It looks great on my laptop but when I view on my phone most of the images are rotated 90 degrees and distorted (stretched) -- I think it's something to do with the "responsive images" technology.

**Comment by iamtakashi** [comment] 2015-12-16 17:40
We haven't heard the issue you've described yet. Without URL it's hard to see what's going on. Can you give us a url where you see the issue?

**Comment by mjglsn** [comment] 2015-12-16 18:56
Sorry, it's my personal site http://gleason.me/amelia with specific posts below.

2 versions of this bug:

(1) Creating the post and adding images on laptop, and then the distorted and rotated images appear on mobile device. So the images in the post look fine on laptop when created on laptop, but when viewed on my mobile phone some images in the post are rotated and distorted/stretched.
Post is here: http://www.gleason.me/amelia/2015/12/16/4-month-birthday-party-3/

(2) creating the post and adding images on my phone, and then the rotated images (no stretching or distortions noticed) appear on my laptop. So in this case, the images in the post look fine on mobile when created via my phone (iphone 6), but when viewed on my laptop some images are rotated (but not stretched or distorted as in the first example). Post is here: http://www.gleason.me/amelia/2015/12/16/visit-with-gi-gi-yoneko-on-dec-13-205/

**Comment by josephfusco** [comment] 2015-12-16 19:31
I can confirm this issue. What a crazy bug. See screenshot from @mjglsn's first link - Safari iOS 9.2 (I should probably plug my phone it :smile: )

![img_1168](https://cloud.githubusercontent.com/assets/6676674/11851524/0f73e650-a401-11e5-8ac6-829dd4ce1077.PNG)

**Comment by iamtakashi** [comment] 2015-12-16 19:43
Could this be isolated to iPhone 6?

I can't replicate the issue with iPhone 5 (iOS9.2) and Nexus 5 (Android 6.0.1)

**Comment by josephfusco** [comment] 2015-12-16 20:13
Seems super strange if we are both running iOS9.2 that we would have different results @joemcgill any insight here as to what may possibly be going on with this image rotation?

**Comment by iamtakashi** [comment] 2015-12-16 20:17
This is very strange. If I click one of image in the post, the image appears rotated.

If this is a theme issue and happens to all, we probably should have heard already.

**Comment by josephfusco** [comment] 2015-12-16 20:27
What was the primary test data used to do theme unit testing?

If it was the [Theme_Unit_Test](https://codex.wordpress.org/Theme_Unit_Test) from the codex there is no edge case for stacked images in the visual editor (not that that would be the issue here). But I agree I think something would have been brought up by now, but then again it has only been around a week since release.

**Comment by iamtakashi** [comment] 2015-12-16 20:33
The theme unit test is just one of them and many people who use trunk have been using with different contents before the official 4.4.

Now I can see the issue on the site in my iPhone 5. Very strange.

**Comment by josephfusco** [comment] 2015-12-16 20:45
Well that is a good sign. So it is related to iOS9.2 then at this point. I am doing some tests now myself on it..

**Comment by mjglsn** [comment] 2015-12-16 20:52
But this post http://www.gleason.me/amelia/2015/12/16/4b-photo-test-phone/ was created on iphone and looks fine on iphone but some images are rotated on PC browser (Chrome 46.0.2490.86) 
And then clicking the rotated images, they show normal.
<img width="1440" alt="screen shot 2015-12-16 at 12 53 55 pm" src="https://cloud.githubusercontent.com/assets/12553560/11853655/1d06d370-a3f4-11e5-8677-66da97e5ae6d.png">
<img width="1440" alt="screen shot 2015-12-16 at 12 54 00 pm" src="https://cloud.githubusercontent.com/assets/12553560/11853662/2003fd82-a3f4-11e5-810d-1215a2267a26.png">

**Comment by josephfusco** [comment] 2015-12-16 20:57
@mjglsn Have you used the image editor in WordPress at all to make rotations? Just curious so we narrow this down.

**Comment by josephfusco** [comment] 2015-12-16 20:59
Also can you please temporarily activate the default twentyfifteen theme and see if this still happens in there?

**Comment by joemcgill** [comment] 2015-12-16 21:03
> Seems super strange if we are both running iOS9.2 that we would have different results @joemcgill any insight here as to what may possibly be going on with this image rotation?

Some browsers respect the EXIF rotation metadata and some do not. iOS Safari happens to be one that does. This is a known issue (see: https://core.trac.wordpress.org/ticket/33051) and not, I believe, specific to this theme.

**Comment by josephfusco** [comment] 2015-12-16 21:05
Thanks Joe :+1:

**Comment by mjglsn** [comment] 2015-12-16 21:05
@josephfusco Yes I have used the image editor to make rotations when I originally noticed the bug. I'll try the twentyfifteen theme

**Comment by iamtakashi** [comment] 2015-12-16 21:08
> Some browsers respect the EXIF rotation metadata and some do not. iOS Safari happens to be one that does.

Oh, that's good to know. As @joemcgill says, it sounds like not the theme specific issue.

**Comment by mjglsn** [comment] 2015-12-16 21:09
With twenty fifteen activated: 
<img width="1440" alt="screen shot 2015-12-16 at 1 07 16 pm" src="https://cloud.githubusercontent.com/assets/12553560/11854034/31a6a772-a3f6-11e5-9e67-aa38250a6d4d.png">
<img width="1440" alt="screen shot 2015-12-16 at 1 08 19 pm" src="https://cloud.githubusercontent.com/assets/12553560/11854036/33ec2516-a3f6-11e5-894b-ec46d0f48436.png">

**Comment by iamtakashi** [comment] 2015-12-16 21:19
OK, I'm closing this as not the theme specific issue. And references:
- https://core.trac.wordpress.org/ticket/33051
- https://core.trac.wordpress.org/ticket/14459

**Closed as completed by iamtakashi** 2015-12-16 21:19 UTC
