### ISSUE TITLE
Page template suggestions

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentysixteen#44] opened 2015-08-29 22:35 UTC
Doing some brainstorming here...

Page Template:
- Portfolio masonry.
- Portfolio standard.
- A nicely stylized blog. (Actually there can be a few different blog templates to choose from.)
- Archive pages.
- A few landing pages.

**Comment by karmatosed** [comment] 2015-08-29 23:01
I would suggest a default theme shouldn't have a lot of page templates. Adding is easy and most people don't want the same. It's probable better practice to provide exactly what the theme type needs. In this case a blog.

**Comment by ihorvorotnov** [comment] 2015-08-29 23:15
@karmatosed well, WordPress is not only for blogs anymore and majority of new sites being built with WordPress are not blogs at all. I'm pretty sure you know there were a lot of discussions on this topic in last few years (but we still don't have a consensus though). I'm not saying we should add eCommerce templates or any other templates which depend on plugins, but at least some simple and common  templates are worth considering. I can think of some custom front page template, a template without sidebar, about page, contacts page to name a few. Creating new templates is pretty easy for those who are familiar with the process, but it might be useful to give some starting points for those who aren't (mostly new and non-techie users) and encourage them to learn more.

Just a real world example. In Russia and Ukraine (markets I am very familiar with) WordPress is still perceived as a blog platform. As a developer making my living with WordPress, I spend a lot of time explaining people what can be done with WordPress and proving it is a lot more than just a blog.

**Comment by karmatosed** [comment] 2015-08-29 23:17
Absolutely, WordPress deals with a lot of types of sites. My point is this theme is aimed at a clear type. That type wouldn't have all those templates. We are not creating one theme for all cases here.

**Comment by ihorvorotnov** [comment] 2015-08-29 23:31
Well, I kind of agree. This theme is nice, minimalistic, type-centric. The same we had with twentythirteen and twentyfifteen. And it's a great successor of twentyfifteen. 

But! 

It limits itself to blogs only out of the box. And people now use WordPress not for blogs, more and more. And this trend is not going anywhere. Looks like we're going to have a theme that would be changed right after installing WordPress by majority of users :)

Don't take me wrong. I like the theme. I will definitely use it for one of my blogs, even before it gets shipped with WordPress. But I still think we can do some brainstorming and come up with a template or two to be added. A front-page, an 'About' page. Front pages are already built-in, they don't rely on any plugins or custom code (both `front-page.php` and `home.php`). 'About me' / 'About us' is also a good candidate - it's present on most of the sites. Adding these templates will encourage new users to learn more, IMHO.

**Comment by paaljoachim** [comment] 2015-08-29 23:49
Since one can switch templates in an easy way in WordPress it seems kinda natural to at least have some templates included to show that the feature is there.

**Comment by celloexpressions** [comment] 2015-08-30 21:22
Who dictated that twentysixteen must be a blog-centric theme? I see no problem with shifting focus slightly to make it more broadly applicable. Especially considering that two of the previous three themes were aimed at blogs and the recent default themes seem to have all been developed internally within Automattic before being announced on make/core and opened to development, which perhaps led to skewed biases.

Regardless, page templates are a core feature that are perhaps underutilized. Core could use a better UI for them, perhaps being contextually available in the Customizer on a per-page basis. If this theme utilized them more, within reason, I could see that helping to encourage iteration in that area of core at the same time. I think this is worth exploring; perhaps if anyone has specific suggestions and can create those designs, they could be considered.

**Comment by SeanChDavis** [comment] 2015-08-30 22:11
I'm completely against anything too specific like a portfolio or eCommerce, as someone already mentioned. However, I definitely agree that page templates would be beneficial.

I think an About Page template fits the theme very well. I feel the same way about a Contact Page, though that would require plugin support (so probably not). A Full-width template would be lovely. I plan to build one for myself right off the bat when I put Twenty Sixteen on my personal site anyway.

I vote for some generic page templates and I'm also willing to help make it happen.

**Comment by senlin** [comment] 2015-08-31 15:31
I suggested a category template in the now closed thread #60 

All twenty-x themes had a separate category template, except twenty fifteen. Apart from the whole discussion blog vs "other" use, there are plenty people that have different categories, for example news and events, and they want to show their posts as such.

Category description (if exists) comes to mind as does for example next/previous post link to be in the same category only, so you don't switch from news to events.

**Comment by ihorvorotnov** [comment] 2015-08-31 15:52
> there are plenty people that have different categories, for example news and events

Sounds solid enough for me. On my new blog theme (which I'm building right now) I have categories 'Tips and Tricks' and 'Tutorials', for example. Posts in first category are short - a small description and code example. Posts in second category are long, sometimes they are series of posts, they have post thumbnails etc (only built-in features though, nothing from plugin territory). The archive pages will look differently, of course.

**Comment by ianstewart** [comment] 2015-09-07 16:54
We discussed this in core-themes today:

https://wordpress.slack.com/archives/core-themes/p1441641898000036

None of the suggestions as-is are moving forward. As-is additional page templates seem "unnecessary." Let's close this discussion-ticket for now and have further suggestions in new tickets accompanied by designed, sketched-out, page templates. That'll let us discuss their merits as page templates one-by-one with concrete examples of implementation. So, not shutting down discussion of page templates but considering them one by one with in-use examples of theme-enhancement.

**Closed as completed by ianstewart** 2015-09-07 16:54 UTC
Labels: discussion
